server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jss
    username: dbuser
    password: dbuser123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
  security:
    user:
      name: ozandor
      password: 321

logging:
  level:
    root: INFO

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,metrics

